// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyFreeFrom.Database;
using MyFreeFrom.Shared.Enums;
using System;

namespace MyFreeFrom.Migrations
{
    [DbContext(typeof(ResturantContext))]
    [Migration("20180524212953_ResturantDBInitialMigration")]
    partial class ResturantDBInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyFreeFrom.Entities.DietOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DietType");

                    b.Property<int?>("ResturantId");

                    b.HasKey("Id");

                    b.HasIndex("ResturantId");

                    b.ToTable("DietOptions");
                });

            modelBuilder.Entity("MyFreeFrom.Entities.Resturant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<string>("County");

                    b.Property<string>("Description");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("Id");

                    b.ToTable("Resturants");
                });

            modelBuilder.Entity("MyFreeFrom.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("DfScore");

                    b.Property<int>("GfScore");

                    b.Property<int>("MfScore");

                    b.Property<int>("PriceRating");

                    b.Property<int?>("ResturantId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ResturantId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MyFreeFrom.Entities.DietOption", b =>
                {
                    b.HasOne("MyFreeFrom.Entities.Resturant")
                        .WithMany("DietOptions")
                        .HasForeignKey("ResturantId");
                });

            modelBuilder.Entity("MyFreeFrom.Entities.Review", b =>
                {
                    b.HasOne("MyFreeFrom.Entities.Resturant")
                        .WithMany("Reviews")
                        .HasForeignKey("ResturantId");
                });
#pragma warning restore 612, 618
        }
    }
}
